spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://133.186.211.156:3306/marketgg_shop
#    username: on7
#    password: ?nk9Wa#^Bg)on71!*,^2=d
    url: jdbc:mysql://127.0.0.1:3306/shop
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true

server:
  port: 7080

  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB
