spring:
  application:
    name: marketgg-shop

  config:
    import: "optional:configserver:http://127.0.0.1:8888"

# Fixme: 경로 수정하기
# uploadPath: /Users/coalong/gh-repos/marketgg/marketgg-server/src/main/resources/static
uploadPath: /Users/johyeonjin/Desktop/temp
inquiryPath: /shop/v1
