spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.211.156:3306/nhn_academy_33
    username: nhn_academy_33
    password: V@B8Rz-hZdINAwjO
#    url: jdbc:mysql://127.0.0.1:3306/shop
#    username: root
#    password: 1234


  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true

server:
  port: 7080

  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB

uploadPath: /Users/coalong/gh-repos/marketgg/marketgg-server/src/main/resources/static

